---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: packer-dinivas-bastion
    image: centos:7
    published_ports:
      - 0.0.0.0:80:80/tcp
    privileged: True
    command: '/sbin/init'
    cap_add: ['SYS_ADMIN', 'SETPCAP']
provisioner:
  name: ansible
  playbooks:
    converge: ../../playbook.yml
  lint:
    name: ansible-lint
verifier:
  name: goss
  lint:
    name: yamllint
